package project.logic;

import project.logic.validation.PercentOffValidator;
import project.objects.Coupon;
import project.objects.ErrorMsg;
import project.objects.Result;
import project.persistence.CouponDatabase;

import java.util.ArrayList;
import java.util.List;

public class CouponManagerLogic {

    CouponDatabase db;

    /**
     * The constructor just needs a reference to the Coupon Database
     * @param db the database
     */
    public CouponManagerLogic(CouponDatabase db) {
        this.db = db;
    }

    /**
     * @return A 2D array of string that can be displayed on a JTable.
     *         Shows the possible coupons that can be applied
     */
    public String[][] getCouponTable() {
        return TableEntryGenerator.genCouponTableEntries(db.getCouponList());
    }

    /**
     * Adds a new coupon that can be used a checkout
     * @param code the code
     * @param percentOff the percent discount that the coupon applies
     * @return returns any errors cause by this operation
     */
    public List<ErrorMsg> addCoupon(String code, String percentOff) {
        List<ErrorMsg> errorMsgs = new ArrayList<>();

        // Check to see if code is empty
        if (code.equals("")) {
            errorMsgs.add(new ErrorMsg("Code cannot be empty!"));
            return errorMsgs;
        }

        // Check to make sure code doesn't already exist
        boolean hasCode = false;
        for (Coupon c: db.getCouponList()) {
            if (c.getCode().equals(code)) {
                hasCode = true;
                break;
            }
        }
        if (hasCode) {
            errorMsgs.add(new ErrorMsg("The code already exists!"));
            return errorMsgs;
        }

        // Validate percentOff
        PercentOffValidator v = new PercentOffValidator();
        Result<Float, List<ErrorMsg>> percentOffResult = v.validate(percentOff);
        if (percentOffResult.getError() != null) {
            return percentOffResult.getError();
        }
        Float oPercentOff = percentOffResult.getResult() / 100.0f;

        // Add new coupon to database
        db.addCoupon(new Coupon(code, oPercentOff));

        return errorMsgs;
    }

    /**
     * Removes a coupon, so it can no longer be used a checkout
     * @param code the code of the coupon to be removed
     * @return returns any errors cause by this operation
     */
    public List<ErrorMsg> removeCoupon(String code) {
        List<ErrorMsg> errorMsgs = new ArrayList<>();

        // Check to see if code is empty
        if (code.equals("")) {
            errorMsgs.add(new ErrorMsg("Code cannot be empty!"));
            return errorMsgs;
        }

        // Check to make sure code doesn't already exist
        boolean hasCode = false;
        for (Coupon c: db.getCouponList()) {
            if (c.getCode().equals(code)) {
                hasCode = true;
                break;
            }
        }
        if (!hasCode) {
            errorMsgs.add(new ErrorMsg("This code doesn't exists!"));
            return errorMsgs;
        }

        // Remove the coupon
        db.removeCoupon(code);

        return errorMsgs;
    }

    /**
     * Allows you to change the percent discount of a coupon that already exists
     * @param code the code for the coupon to be updated
     * @param percentOff the new percent discount
     * @return any errors generated by this operation
     */
    public List<ErrorMsg> updateCoupon(String code, String percentOff) {
        List<ErrorMsg> errorMsgs = new ArrayList<>();

        // Check to see if code is empty
        if (code.equals("")) {
            errorMsgs.add(new ErrorMsg("Code cannot be empty!"));
            return errorMsgs;
        }

        // Check to make sure code doesn't already exist
        boolean hasCode = false;
        for (Coupon c: db.getCouponList()) {
            if (c.getCode().equals(code)) {
                hasCode = true;
                break;
            }
        }
        if (!hasCode) {
            errorMsgs.add(new ErrorMsg("This code doesn't exists!"));
            return errorMsgs;
        }

        // Validate percentOff
        PercentOffValidator v = new PercentOffValidator();
        Result<Float, List<ErrorMsg>> percentOffResult = v.validate(percentOff);
        if (percentOffResult.getError() != null) {
            return percentOffResult.getError();
        }
        Float oPercentOff = percentOffResult.getResult() / 100.0f;

        // Update coupon in database
        db.replaceCoupon(new Coupon(code, oPercentOff));

        return errorMsgs;
    }
}