package project.logic;

import project.objects.ErrorMsg;
import project.objects.ProductList;

import java.util.List;

public interface ILogic {
    /**
     * Add a product to the database, the inputs are all the strings that
     * were directly inputed by the user
     * @param name
     * @param quantity
     * @param price
     * @param expiryDate
     * @return any errors generated by the operation
     */
    List<ErrorMsg> addProduct(String name, String quantity, String price, String expiryDate);

    /**
     * Remove a product
     * @param barcode a string from the user that should be the barcode of
     *                the product to be removed
     * @return any errors generated by the operation
     */
    List<ErrorMsg> removeProduct(String barcode);

    /**
     * Replace a product in the database with an updated version of itself
     * If you don't want to change a certain field, then leave it blank
     * @param barcode
     * @param name
     * @param quantity
     * @param price
     * @param expiryDate
     * @return any errors generated by the operation
     */
    List<ErrorMsg> updateProduct(String barcode, String name, String quantity, String price, String expiryDate);

    /**
     * Get the list of all products currently in the database
     * @return A list of all products in the database
     */
    ProductList getProductList();
}
