/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package project;

import com.google.gson.*;

public class App {
    public static void main(String[] args) {
        Gson gson = new Gson();

        MyClass mc1 = new MyClass(100);
        String json = gson.toJson(mc1);
        MyClass mc2 = gson.fromJson(json, MyClass.class);

        System.out.println(mc1);
        System.out.println(json);
        System.out.println(mc2);
    }
}
